language: go
go:
- 1.7.1
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="Jose Labra"
  - GIT_EMAIL="labra@uniovi.es"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
  - TEMP_DIR=$(sudo mktemp -d /tmp/$REPO_NAME.XXXX)
before_script:
- git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
- go get -u -v github.com/spf13/hugo
script:
- git submodule init
- hugo
after_success:
- chmod a+x ./scripts/deploy.sh
- "./scripts/deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_5149d9ecf627_key -iv $encrypted_5149d9ecf627_iv
  -in travis_key.enc -out travis_key -d
