# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="Jose Labra"
  - GIT_EMAIL="labra@uniovi.es"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
  - TEMP_DIR=$(sudo mktemp -d /tmp/$REPO_NAME.XXXX)

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  # Build our site
  - chmod +x binaries/hugo
  - binaries/hugo
  # Create a CNAME file which maps our site to our custom domain
  # - echo 'freshswift.net' > public/CNAME

after_success:
- chmod a+x ./scripts/deploy.sh
- "./scripts/deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_a5dbcd39374d_key -iv $encrypted_a5dbcd39374d_iv
  -in travis_key.enc -out travis_key -d

# Deploy to GitHub pages
#deploy:
#  provider: pages
#  skip_cleanup: true
  # Our token is set in travis-ci.org dashboard
#  github_token: $GITHUB_TOKEN
#  local_dir: public
#  on:
#    branch: master